version: '3.4'

services:
  event-management-system.api:
    image: ${DOCKER_REGISTRY-}event-management-system
    build:
      context: .
      dockerfile: EventManagementSystem/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
  event-management-system.db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event-management-system
    volumes:
      - event-management-system-db:/var/lib/postgresql/data    
    ports:
      - 5432:5432
 
volumes:
  event-management-system-db: